baseURL = "https://hexagrimoire.github.io/"
languageCode = "en-us"
title = "Accessibility → Up to 11!"
theme = "anatole"

# Parameters

[params]
title = "Accessibility → Up to 11!"
author = "Dani Devesa"
description = "Dani Devesa"
profilePicture = "images/myself.jpg"
keywords = ""


## Social links
[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/dadederk"

[[params.socialIcons]]
icon = "fa-medium"
title = "Medium"
url = "https://medium.com/@dadederk"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/danieldevesa/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/dadederk/"

## [[params.socialIcons]]
## icon = "fa-stackoverflow"
## title = "Stackoverflow"
## url = "https://stackoverflow.com/users/1336597/dadederk"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/dadederk/"

## Menu items

[menu]

  [[menu.main]]
  name = "Posts"
  identifier = "posts"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/post/"

  [[menu.main]]
  name = "Book"
  weight = 300
  identifier = "book"
  url = "https://amzn.to/2PDr9cs"

  [[menu.main]]
  name = "RSS"
  weight = 400
  identifier = "rss"
  url = "https://dadederk.github.io/index.xml"