baseURL = "https://hexagrimoire.github.io/"
languageCode = "en-us"
title = "GadgetLogs"
theme = "anatole"

# Parameters

[params]
title = "GadgetLogs"
author = "hexagrimoire (UenoSouhei)"
description = "hexagrimoire (UenoSouhei)"
profilePicture = "images/4945590.png"
keywords = ""


## Social links
[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/hexagrimoire"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/hexagrimoire"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/hexagrimoire/"

## Menu items

[menu]

  [[menu.main]]
  name = "Posts"
  identifier = "posts"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/post/"

  [[menu.main]]
  name = "WorkNews"
  weight = 300
  identifier = "WorkNews"
  url = "https://customers.microsoft.com/ja-jp/story/1364935832890127585-game-studio-gaming-azure-jp-japan"

  [[menu.main]]
  name = "RSS"
  weight = 400
  identifier = "rss"
  url = "https://hexagrimoire.github.io/index.xml"